### ISSUE TITLE
violations are not cleared at the beginning of validate()

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [jschaedl/iban-validation#103]
Following code was working in 1.x but fails in 2.x because `validations` array is not cleared:

```php

$validator = new Validator();

if ($validator->validate(/* invalid iban */) || $validator->validate(/* valid iban */)) {
  echo "One of the ibans is correct";
}
```

**Comment by jschaedl** [comment]
Thanks for reporting this. Would you like to provide a fix? Like you said, clearing the `violations` array at the beginning of the `Validator::validate` method (https://github.com/jschaedl/iban-validation/blob/master/src/Validator.php#L53) should fix it.

**Comment by jacekkarczmarczyk** [comment]
I'll give it a try

**Comment by jacekkarczmarczyk** [comment]
Cheers, thanks for release!
