### ISSUE TITLE
Migrate from jschaedl/iban

### ISSUE THREAD

**Issue by davidvandemaele** [jschaedl/iban-validation#11]
When I migrate to the new iban-validation package and try to validate an iban number, I get the following error:

:  Uncaught Error: Class 'Symfony\Component\Yaml\Parser' not found in lib/external/packages/symfony/yaml/Yaml.php:77
Stack trace:
#0 lib/external/packages/jschaedl/iban-validation/src/Swift/RegistryLoader.php(41): Symfony\Component\Yaml\Yaml::parse('AD:\n    country...')
#1 lib/external/packages/jschaedl/iban-validation/src/Swift/Registry.php(37): Iban\Validation\Swift\RegistryLoader-&gt;load()
#2 lib/external/packages/jschaedl/iban-validation/src/Validator.php(84): Iban\Validation\Swift\Registry-&gt;__construct()
#3 lib/model/Supplier.php(40): Iban\Validation\Validator-&gt;__construct()

**Comment by xabbuh** [comment]
Does the file `lib/external/packages/symfony/yaml/Parser.php` exist? How is your autoloading configured?

**Comment by davidvandemaele** [comment]
Yes it did. If I tried to do the same via commandline, I got the same error. If I included the Parser class and parsed the string, it worked.
I've uninstalled the iban-validation package and gave it another try.
Now it is working.
