### ISSUE TITLE
bcmod(): bcmath function argument is not well-formed in PHP 7.4

### ISSUE THREAD

**Issue by bigwhoop** [jschaedl/iban-validation#22]
Hi,

PHP 7.4 no longer suppresses malformed input for bcmath functions. See https://www.php.net/manual/en/migration74.incompatible.php

If you try to validate the IBAN `MCBKCWCU25727002` for example, the library will use `BK` as part of the checksum and make the call `bcmod('12321230257270022212BK', '97', 0)` in \Iban\Validation\Validator::local_bcmod. As you can see the first argument is not numeric and it leads to the error mentioned in the title.

**Comment by bigwhoop** [comment]
Hi. Could you please release a new version that includes this fix? Thanks

**Comment by jschaedl** [comment]
@bigwhoop Here you go: https://github.com/jschaedl/iban-validation/releases/tag/v1.5
