### ISSUE TITLE
Get the bank code part

### ISSUE THREAD

**Issue by sdecandelario** [jschaedl/iban-validation#30]
Hello, I think it's interesting the funcion that you can get the bank code of an iban for example to know the bank of the account and can associate with a table of banks that you have or whatever, what do you think?

**Comment by jschaedl** [comment]
Hi @sdecandelario.

Are you looking for something like this https://github.com/jschaedl/Bav ?

**Comment by sdecandelario** [comment]
@jschaedl yes I think something similar, but i need to be valid for any account not only germany. I used this (https://github.com/globalcitizen/php-iban/blob/master/php-iban.php#L191), but I don't like so much how this library is made
