### ISSUE TITLE
v1.8.0 BC Break - missing RegistryLoader class

### ISSUE THREAD

**Issue by AymDev** [jschaedl/iban-validation#67]
Hello, I found a breaking change in a project I work on using a `^1.2` version constraint where the build fails when installing **v1.8** as the `Iban\Validation\Swift\RegistryLoader` class does not exist anymore.

 - [src/Swift at v1.7](https://github.com/jschaedl/iban-validation/tree/v1.7.0/src/Swift)
 - [src/Swift at v1.8](https://github.com/jschaedl/iban-validation/tree/v1.8.0/src/Swift)

Was it intentional or a refactor targetting a **v2** ?

**Comment by jschaedl** [comment]
Thanks for reporting this. That was a mistake. The registry loader was marked as final in v.1.7.0 and should only be removed in v2.0.0. I will fix it as soon as possible. Please use v1.7.0 in the meantime.

**Comment by jschaedl** [comment]
@AymDev Could you please check if this fixes the issue. Thank you.

**Comment by AymDev** [comment]
Hi @jschaedl and thanks for the quick reply. Yes this should fix the issue.
